version: 2.1
orbs:
  slack: circleci/slack@4.13.3
jobs:
  automated-api-tests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Postman CLI
          command: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - run:
          name: Login using your API key
          command: postman login --with-api-key $POSTMAN_API_KEY
      - run: |
            postman collection run "55936694-24333855-5a26-49c7-b76b-9d69f0e56305"

workflows:
  version: 2
  automated-api-tests:
    jobs:
      - automated-api-tests
